version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Mapeia o diretório local para o diretório do container
    environment:
      - NODE_ENV=development
